# Generated by Django 4.2.3 on 2023-08-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_equipo_mantenimiento_operario_delete_entregable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
    ]
