# Generated by Django 4.2.3 on 2023-08-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_empleado_delete_operario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='referencia',
            field=models.CharField(max_length=6),
        ),
    ]
