# Generated by Django 4.2.3 on 2023-08-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_equipo_referencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(default=0),
        ),
    ]
