# Generated by Django 4.2.3 on 2023-08-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_empleado_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='dni',
        ),
    ]
