# Generated by Django 4.2.3 on 2023-08-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_remove_empleado_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comision', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='referencia',
            field=models.IntegerField(),
        ),
    ]
