# Generated by Django 4.2.3 on 2023-08-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_curso_alter_equipo_referencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='referencia',
            field=models.CharField(max_length=6),
        ),
    ]
